SELECT
  foo.id,
  foo."nameId_EN" AS name_en,
  foo."nameId_ES" AS name_es,
  foo."nameId_FR" AS name_fr,
  foo."nameId_DE" AS name_de,
  foo."nameId_PT" AS name_pt,
  foo."nameId_IT" AS name_it,
  foo."typeId" AS type_id,
  foo."descriptionId_EN" AS desc_en,
  foo."descriptionId_ES" AS desc_es,
  foo."descriptionId_FR" AS desc_fr,
  foo."descriptionId_DE" AS desc_de,
  foo."descriptionId_PT" AS desc_pt,
  foo."descriptionId_IT" AS desc_it,
  foo."iconId" AS icon_id,
  foo.level,
  foo."realWeight" AS pods,
  foo.price,
  foo."itemSetId" AS item_set_id,
  foo.criteria,
  0 AS pet_food_xp,
  0 AS nuggets
FROM
  (
    SELECT
      item.id,
      item."nameId_EN",
      item."nameId_ES",
      item."nameId_FR",
      item."nameId_DE",
      item."nameId_PT",
      item."nameId_IT",
      item."typeId",
      item."descriptionId_EN",
      item."descriptionId_ES",
      item."descriptionId_FR",
      item."descriptionId_DE",
      item."descriptionId_PT",
      item."descriptionId_IT",
      item."iconId",
      item.level,
      item."realWeight",
      item.cursed,
      item."useAnimationId",
      item.usable,
      item.targetable,
      item.exchangeable,
      item.price,
      item."twoHanded",
      item.etheral,
      item."itemSetId",
      item.criteria,
      item."criteriaTarget",
      item."hideEffects",
      item.enhanceable,
      item."nonUsableOnAnother",
      item."appearanceId",
      item."secretRecipe",
      item."recipeSlots",
      item."recipeIds",
      item."dropMonsterIds",
      item."dropTemporisMonsterIds",
      item."objectIsDisplayOnWeb",
      item."bonusIsSecret",
      item."evolutiveEffectIds",
      item."favoriteSubAreas",
      item."favoriteSubAreasBonus",
      item."craftXpRatio",
      item."needUseConfirm",
      item."isDestructible",
      item."isSaleable",
      item."isColorable",
      item."isLegendary",
      item."craftVisible",
      item."craftConditional",
      item."craftFeasible",
      item.visibility,
      item."recyclingNuggets",
      item."favoriteRecyclingSubareas",
      item."containerIds",
      item."resourcesBySubarea",
      item."importantNoticeId_EN",
      item."importantNoticeId_ES",
      item."importantNoticeId_FR",
      item."importantNoticeId_DE",
      item."importantNoticeId_PT",
      item."importantNoticeId_IT",
      item."changeVersion",
      item."tooltipExpirationDate"
    FROM
      dofus2_raw.item
    UNION
    SELECT
      weapon.id,
      weapon."nameId_EN",
      weapon."nameId_ES",
      weapon."nameId_FR",
      weapon."nameId_DE",
      weapon."nameId_PT",
      weapon."nameId_IT",
      weapon."typeId",
      weapon."descriptionId_EN",
      weapon."descriptionId_ES",
      weapon."descriptionId_FR",
      weapon."descriptionId_DE",
      weapon."descriptionId_PT",
      weapon."descriptionId_IT",
      weapon."iconId",
      weapon.level,
      weapon."realWeight",
      weapon.cursed,
      weapon."useAnimationId",
      weapon.usable,
      weapon.targetable,
      weapon.exchangeable,
      weapon.price,
      weapon."twoHanded",
      weapon.etheral,
      weapon."itemSetId",
      weapon.criteria,
      weapon."criteriaTarget",
      weapon."hideEffects",
      weapon.enhanceable,
      weapon."nonUsableOnAnother",
      weapon."appearanceId",
      weapon."secretRecipe",
      weapon."recipeSlots",
      weapon."recipeIds",
      weapon."dropMonsterIds",
      weapon."dropTemporisMonsterIds",
      weapon."objectIsDisplayOnWeb",
      weapon."bonusIsSecret",
      weapon."evolutiveEffectIds",
      weapon."favoriteSubAreas",
      weapon."favoriteSubAreasBonus",
      weapon."craftXpRatio",
      weapon."needUseConfirm",
      weapon."isDestructible",
      weapon."isSaleable",
      weapon."isColorable",
      weapon."isLegendary",
      weapon."craftVisible",
      weapon."craftConditional",
      weapon."craftFeasible",
      weapon.visibility,
      weapon."recyclingNuggets",
      weapon."favoriteRecyclingSubareas",
      weapon."containerIds",
      weapon."resourcesBySubarea",
      weapon."importantNoticeId_EN",
      weapon."importantNoticeId_ES",
      weapon."importantNoticeId_FR",
      weapon."importantNoticeId_DE",
      weapon."importantNoticeId_PT",
      weapon."importantNoticeId_IT",
      weapon."changeVersion",
      weapon."tooltipExpirationDate"
    FROM
      dofus2_raw.weapon
  ) foo
ORDER BY
  foo.id;